LOCALIZATION = {
    "ru": {
        # Action Bar
        "pick_files": "Выбрать файлы",
        "pick_folder": "Выбрать папку",
        "clear": "Очистить",
        "clean_metadata": "Очистить метаданные",
        "ready": "Готово!",
        "processing": "Обработка...",
        # Stats Panel
        "total": "Всего",
        "processed": "Обработано",
        "successful": "Успешно",
        "errors": "Ошибки",
        "progress": "Прогресс",
        "statistics": "Статистика",
        # Progress Card
        "ready_to_work": "Готов к работе",
        "select_files_to_start": "Выберите файлы",
        "files_selected": "Файлы выбраны",
        "ready_to_process_files": "Готово: {count} файлов",
        "processing_now": "Обработка...",
        "processed_files_count": "{processed}/{total}",
        "done": "Готово!",
        "all_files_processed": "Готово: {count}",
        "completed_with_errors": "Готово с ошибками",
        "success_count_errors_count": "ОК: {success}, ошибок: {failed}",
        "starting_cleanup": "Начинаю очистку...",
        "preparing_files": "Подготовка к обработке файлов",
        "processing_file_count": "Обрабатываю файл {i}/{total}",
        "file": "Файл: {filename}",
        # File Card
        "file_size": "{size:.2f} KB",
        "status_pending": "Ожидание...",
        "status_processing": "Обработка...",
        "status_success": "Успех",
        "status_error": "Ошибка",
        "status_cleaned": "Очищено",
        # Main App
        "app_title": "Metadata Cleaner",
        "drop_files_here": "Перетащите файлы сюда или нажмите 'Выбрать файлы'",
        "selected_files": "Выбранные файлы",
        "no_files_selected": "Файлы не выбраны",
        "use_buttons_to_select": "Нажмите кнопки выше для выбора файлов или папки",
        "completion_all_success": "✅ Все {total} файлов успешно обработаны!",
        "completion_with_errors": "⚠️ Обработано {successful} из {total} файлов",
        "details": "Детали",
        "detailed_results": "Детальные результаты обработки",
        "close": "Закрыть",
        # Settings Dialog
        "settings": "Настройки",
        "cancel": "Отмена",
        "reset_defaults": "По умолчанию",
        "save": "Сохранить",
        "general": "Общие",
        "images": "Изображения",
        "documents": "Документы",
        "pdf": "PDF",
        "video": "Видео",
        "about": "О программе",
        "main_settings": "Основные настройки",
        "theme": "Тема",
        "system_theme": "Системная",
        "light_theme": "Светлая",
        "dark_theme": "Темная",
        "language": "Язык",
        "russian": "Русский",
        "english": "English",
        "file_processing": "Обработка файлов",
        "processing_settings": "Настройки обработки",
        "max_threads": "Количество потоков",
        "show_notifications": "Показывать уведомления",
        "auto_close_after_completion": "Закрывать после завершения",
        "show_detailed_logs": "Детальные логи",
        "output_mode": "Режим вывода",
        "create_copy": "Создать копию",
        "overwrite": "Перезаписать",
        "backup_and_overwrite": "Бэкап и перезапись",
        "create_backups": "Создавать резервные копии",
        "info": "Информация",
        "info_create_copy": "• Создать копию: оригинальные файлы не изменяются",
        "info_overwrite": "• Перезаписать: изменения применяются к оригиналам",
        "info_backup_overwrite": "• Бэкап и перезапись: создается резервная копия, затем изменяется оригинал",
        "metadata_for_images": "Метаданные для изображений",
        "metadata_for_documents": "Метаданные для документов",
        "metadata_for_pdf": "Метаданные для PDF файлов",
        "metadata_for_video": "Метаданные для видеофайлов",
        "select_all": "Выбрать все",
        "deselect_all": "Снять все",
        "gps_coords": "GPS координаты",
        "gps_desc": "Удалить данные о местоположении",
        "camera_info": "Информация о камере",
        "camera_desc": "Модель камеры, настройки съемки",
        "exif_data": "EXIF данные",
        "exif_desc": "Техническая информация о фото",
        "author": "Автор",
        "author_desc_img": "Информация о фотографе",
        "author_desc_doc": "Имя создателя документа",
        "author_desc_pdf": "Создатель PDF",
        "comments": "Комментарии",
        "comments_desc_img": "Описания и комментарии к фото",
        "comments_desc_doc": "Примечания к документу",
        "created_date": "Дата создания",
        "created_date_desc_img": "Дата и время съемки",
        "created_date_desc_doc": "Когда был создан",
        "created_date_desc_pdf": "Дата создания PDF",
        "created_date_desc_vid": "Дата и время съемки",
        "title": "Заголовок",
        "title_desc_doc": "Название документа",
        "title_desc_pdf": "Название документа",
        "subject": "Тема",
        "subject_desc_doc": "Тематика документа",
        "subject_desc_pdf": "Описание содержания",
        "keywords": "Ключевые слова",
        "keywords_desc_doc": "Теги и метки",
        "keywords_desc_pdf": "Теги для поиска",
        "modified_date": "Дата изменения",
        "modified_date_desc_doc": "Последнее изменение",
        "modified_date_desc_pdf": "Последнее изменение",
        "modified_date_desc_vid": "Последнее изменение файла",
        "revision": "Ревизии",
        "revision_desc": "История изменений",
        "camera_desc_vid": "Модель устройства записи",
        "about_program": "О программе",
        "app_version": "Версия 1.0.0",
        "app_description": "Metadata Cleaner - это современное open-source приложение для безопасного удаления метаданных из различных типов файлов. Защитите свою приватность, удалив скрытую информацию из фотографий, документов, PDF и видеофайлов.",
        "supported_formats": "Поддерживаемые форматы",
        "supported_images_formats": "JPG, JPEG, PNG, GIF, HEIC, HEIF",
        "supported_docs_formats": "DOCX, PPTX, XLSX",
        "supported_pdf_formats": "PDF",
        "supported_video_formats": "MP4, MOV",
        "creator": "Создатель",
        "creator_desc_pdf": "Программа создания PDF",
        "author_desc_vid": "Автор или создатель видео",
        "comments_desc_vid": "Описания и комментарии к видео",
        "copyright": "© 2025 Metadata Cleaner",
        "license_flet": "Лицензия MIT • Сделано с ❤️ на Python и Flet",
        "github_link": "https://github.com/AntGalanin06/Metadata_Cleaner",
        "privacy_security": "Приватность и безопасность",
        "privacy_info": "• Все файлы обрабатываются локально на вашем устройстве\n• Никакие данные не передаются в интернет\n• Исходный код открыт для проверки\n• Создание резервных копий по желанию",
        "legal_info": "Документы",
        "terms_privacy": "Пользовательское соглашение • Политика конфиденциальности",
        "privacy_policy": "Политика конфиденциальности",
        "terms_of_service": "Пользовательское соглашение",
        "read_privacy_policy": "Политика конфиденциальности",
        "read_terms_of_service": "Пользовательское соглашение",
        "settings_saved": "✅ Настройки сохранены",
        # Новые уведомления
        "scanning_folder": "🔍 Сканирую папку и все подпапки...",
        "files_found": "✅ Найдено {count} файлов для обработки из {total} просканированных",
        "no_files_found": "⚠️ Поддерживаемые файлы не найдены (просканировано: {total})",
        "files_added": "✅ Добавлено файлов: {count}",
        "files_added_with_duplicates": "✅ Добавлено файлов: {count} (пропущено дубликатов: {duplicates})",
        "unknown_error": "Неизвестная ошибка",
        "ok": "OK",
        "pick_files_dialog_title": "Выберите файлы для очистки метаданных",
        "pick_folder_dialog_title": "Выберите папку для сканирования файлов",
        "switch_theme": "Переключить тему",
        "remove_from_list": "Удалить из списка",
        
        # Detailed results dialog
        "no_results_yet": "Результаты обработки появятся здесь",
        "total_files": "Всего файлов",
        "failed": "Не удалось",
        "metadata_cleaned_count": "Очищено {count} полей метаданных",
        "cleaned_metadata": "Очищенные метаданные:",
        "no_metadata_found": "Метаданные не найдены",
        "file_had_no_metadata": "Файл не содержал метаданных для очистки",
        "processing_failed": "Ошибка обработки",
        "processing_time": "Время: {time}",
        
        # Metadata settings translations
        "exif_author": "Автор фотографии",
        "exif_author_desc": "Информация о фотографе в EXIF",
        "exif_copyright": "Авторские права",
        "exif_copyright_desc": "Copyright информация в EXIF",
        "exif_datetime": "Дата съемки",
        "exif_datetime_desc": "Дата и время съемки из EXIF",
        "exif_camera": "Камера и настройки",
        "exif_camera_desc": "Модель камеры, объектив, параметры съемки",
        "exif_software": "ПО обработки",
        "exif_software_desc": "Программное обеспечение для обработки фото",
        "gps_coords": "GPS координаты",
        "gps_coords_desc": "Точные координаты места съемки",
        "gps_altitude": "GPS высота",
        "gps_altitude_desc": "Высота над уровнем моря",
        "camera_owner": "Владелец камеры",
        "camera_owner_desc": "Имя владельца камеры",
        "camera_serial": "Серийный номер",
        "camera_serial_desc": "Серийные номера камеры и объектива",
        "user_comments": "Комментарии",
        "user_comments_desc": "Пользовательские комментарии",
        "author": "Автор документа",
        "author_desc": "Имя создателя документа",
        "last_modified_by": "Последний редактор",
        "last_modified_by_desc": "Кто последний изменял документ",
        "company": "Компания",
        "company_desc": "Организация-создатель документа",
        "created": "Дата создания",
        "created_desc": "Когда документ был создан",
        "modified": "Дата изменения",
        "modified_desc": "Последнее изменение документа",
        "last_printed": "Дата печати",
        "last_printed_desc": "Когда документ печатался",
        "revision": "Номер ревизии",
        "revision_desc": "Версия и история изменений",
        "version": "Версия документа",
        "version_desc": "Номер версии документа",
        "content_status": "Статус контента",
        "content_status_desc": "Статус готовности документа",
        "category": "Категория",
        "category_desc": "Тематическая категория",
        "language": "Язык документа",
        "language_desc": "Язык содержимого",
        "identifier": "Идентификатор",
        "identifier_desc": "Уникальный ID документа",
        "title": "Заголовок",
        "title_desc": "Название документа (сохраняется)",
        "subject": "Тема",
        "subject_desc": "Тематика документа (сохраняется)",
        "keywords": "Ключевые слова",
        "keywords_desc": "Теги для поиска (сохраняются)",
        "comments": "Комментарии",
        "comments_desc": "Описание содержания (сохраняется)",
        "creator": "Создатель",
        "creator_desc": "Программа создания PDF",
        "producer": "Производитель",
        "producer_desc": "ПО для генерации PDF",
        "encoder": "Энкодер",
        "encoder_desc": "Программа/устройство записи",
        "creation_time": "Дата создания",
        "creation_time_desc": "Время съемки/создания видео",
        "location": "Локация",
        "location_desc": "Информация о местоположении",
        "major_brand": "Формат контейнера",
        "major_brand_desc": "Основной тип видеофайла",
        "compatible_brands": "Совместимость",
        "compatible_brands_desc": "Поддерживаемые форматы",
        "comment": "Комментарии",
        "comment_desc": "Краткое описание (сохраняется)",
        "description": "Описание",
        "description_desc": "Подробное описание (сохраняется)",
    },
    "en": {
        # Action Bar
        "pick_files": "Pick Files",
        "pick_folder": "Pick Folder",
        "clear": "Clear",
        "clean_metadata": "Clean Metadata",
        "ready": "Ready!",
        "processing": "Processing...",
        # Stats Panel
        "total": "Total",
        "processed": "Processed",
        "successful": "Successful",
        "errors": "Errors",
        "progress": "Progress",
        "statistics": "Statistics",
        # Progress Card
        "ready_to_work": "Ready to work",
        "select_files_to_start": "Select files",
        "files_selected": "Files selected",
        "ready_to_process_files": "Ready: {count} files",
        "processing_now": "Processing...",
        "processed_files_count": "{processed}/{total}",
        "done": "Done!",
        "all_files_processed": "Done: {count}",
        "completed_with_errors": "Done with errors",
        "success_count_errors_count": "OK: {success}, Errors: {failed}",
        "starting_cleanup": "Starting cleanup...",
        "preparing_files": "Preparing files for processing",
        "processing_file_count": "Processing file {i}/{total}",
        "file": "File: {filename}",
        # File Card
        "file_size": "{size:.2f} KB",
        "status_pending": "Pending...",
        "status_processing": "Processing...",
        "status_success": "Success",
        "status_error": "Error",
        "status_cleaned": "Cleaned",
        # Main App
        "app_title": "Metadata Cleaner",
        "drop_files_here": "Drag and drop files here or click 'Pick Files'",
        "selected_files": "Selected Files",
        "no_files_selected": "No files selected",
        "use_buttons_to_select": "Use the buttons above to select files or a folder",
        "completion_all_success": "✅ All {total} files processed successfully!",
        "completion_with_errors": "⚠️ Processed {successful} out of {total} files",
        "details": "Details",
        "detailed_results": "Detailed Processing Results",
        "close": "Close",
        # Settings Dialog
        "settings": "Settings",
        "cancel": "Cancel",
        "reset_defaults": "Defaults",
        "save": "Save",
        "general": "General",
        "images": "Images",
        "documents": "Documents",
        "pdf": "PDF",
        "video": "Video",
        "about": "About",
        "main_settings": "Main Settings",
        "theme": "Theme",
        "system_theme": "System",
        "light_theme": "Light",
        "dark_theme": "Dark",
        "language": "Language",
        "russian": "Русский",
        "english": "English",
        "file_processing": "File Processing",
        "processing_settings": "Processing Settings",
        "max_threads": "Number of threads",
        "show_notifications": "Show notifications",
        "auto_close_after_completion": "Auto-close after completion",
        "show_detailed_logs": "Detailed logs",
        "output_mode": "Output Mode",
        "create_copy": "Create a copy",
        "overwrite": "Overwrite",
        "backup_and_overwrite": "Backup and overwrite",
        "create_backups": "Create backups",
        "info": "Information",
        "info_create_copy": "• Create a copy: original files are not modified",
        "info_overwrite": "• Overwrite: changes are applied to the originals",
        "info_backup_overwrite": "• Backup and overwrite: a backup is created, then the original is modified",
        "metadata_for_images": "Metadata for Images",
        "metadata_for_documents": "Metadata for Documents",
        "metadata_for_pdf": "Metadata for PDF files",
        "metadata_for_video": "Metadata for Video files",
        "select_all": "Select All",
        "deselect_all": "Deselect All",
        "gps_coords": "GPS Coordinates",
        "gps_desc": "Remove location data",
        "camera_info": "Camera Information",
        "camera_desc": "Camera model, shooting settings",
        "exif_data": "EXIF Data",
        "exif_desc": "Technical information about the photo",
        "author": "Author",
        "author_desc_img": "Photographer information",
        "author_desc_doc": "Document creator's name",
        "author_desc_pdf": "PDF creator",
        "comments": "Comments",
        "comments_desc_img": "Descriptions and comments on the photo",
        "comments_desc_doc": "Notes on the document",
        "created_date": "Creation Date",
        "created_date_desc_img": "Date and time of shooting",
        "created_date_desc_doc": "When it was created",
        "created_date_desc_pdf": "PDF creation date",
        "created_date_desc_vid": "Date and time of shooting",
        "title": "Title",
        "title_desc_doc": "Document title",
        "title_desc_pdf": "Document title",
        "subject": "Subject",
        "subject_desc_doc": "Document subject matter",
        "subject_desc_pdf": "Content description",
        "keywords": "Keywords",
        "keywords_desc_doc": "Tags and labels",
        "keywords_desc_pdf": "Tags for searching",
        "modified_date": "Modification Date",
        "modified_date_desc_doc": "Last modification",
        "modified_date_desc_pdf": "Last modification",
        "modified_date_desc_vid": "Last file modification",
        "revision": "Revisions",
        "revision_desc": "Change history",
        "camera_desc_vid": "Recording device model",
        "about_program": "About",
        "app_version": "Version 1.0.0",
        "app_description": "Metadata Cleaner is a modern open-source application for safely removing metadata from various file types. Protect your privacy by removing hidden information from photos, documents, PDFs, and video files.",
        "supported_formats": "Supported Formats",
        "supported_images_formats": "JPG, JPEG, PNG, GIF, HEIC, HEIF",
        "supported_docs_formats": "DOCX, PPTX, XLSX",
        "supported_pdf_formats": "PDF",
        "supported_video_formats": "MP4, MOV",
        "creator": "Creator",
        "creator_desc_pdf": "PDF creation software",
        "author_desc_vid": "Video author or creator",
        "comments_desc_vid": "Video descriptions and comments",
        "copyright": "© 2025 Metadata Cleaner",
        "license_flet": "MIT License • Made with ❤️ using Python and Flet",
        "github_link": "https://github.com/AntGalanin06/Metadata_Cleaner",
        "privacy_security": "Privacy & Security",
        "privacy_info": "• All files are processed locally on your device\n• No data is transmitted to the internet\n• Source code is open for verification\n• Optional backup creation",
        "legal_info": "Documents",
        "terms_privacy": "Terms of Service • Privacy Policy",
        "privacy_policy": "Privacy Policy",
        "terms_of_service": "Terms of Service",
        "read_privacy_policy": "Privacy Policy",
        "read_terms_of_service": "Terms of Service",
        "settings_saved": "✅ Settings saved",
        # New notifications
        "scanning_folder": "🔍 Scanning folder and all subfolders...",
        "files_found": "✅ Found {count} files for processing out of {total} scanned",
        "no_files_found": "⚠️ No supported files found (scanned: {total})",
        "files_added": "✅ Files added: {count}",
        "files_added_with_duplicates": "✅ Files added: {count} (duplicates skipped: {duplicates})",
        "unknown_error": "Unknown error",
        "ok": "OK",
        "pick_files_dialog_title": "Select files to clean metadata",
        "pick_folder_dialog_title": "Select folder to scan for files",
        "switch_theme": "Switch theme",
        "remove_from_list": "Remove from list",
        
        # Detailed results dialog
        "no_results_yet": "Processing results will appear here",
        "total_files": "Total Files",
        "failed": "Failed",
        "metadata_cleaned_count": "Cleaned {count} metadata fields",
        "cleaned_metadata": "Cleaned metadata:",
        "no_metadata_found": "No metadata found",
        "file_had_no_metadata": "File contained no metadata to clean",
        "processing_failed": "Processing failed",
        "processing_time": "Time: {time}",
        
        # Metadata settings translations
        "exif_author": "Photo Author",
        "exif_author_desc": "Photographer information in EXIF",
        "exif_copyright": "Copyright",
        "exif_copyright_desc": "Copyright information in EXIF",
        "exif_datetime": "Shot Date",
        "exif_datetime_desc": "Date and time of shooting from EXIF",
        "exif_camera": "Camera & Settings",
        "exif_camera_desc": "Camera model, lens, shooting parameters",
        "exif_software": "Processing Software",
        "exif_software_desc": "Software for photo processing",
        "gps_coords": "GPS Coordinates",
        "gps_coords_desc": "Exact coordinates of shooting location",
        "gps_altitude": "GPS Altitude",
        "gps_altitude_desc": "Height above sea level",
        "camera_owner": "Camera Owner",
        "camera_owner_desc": "Camera owner's name",
        "camera_serial": "Serial Number",
        "camera_serial_desc": "Camera and lens serial numbers",
        "user_comments": "Comments",
        "user_comments_desc": "User comments",
        "author": "Document Author",
        "author_desc": "Document creator's name",
        "last_modified_by": "Last Editor",
        "last_modified_by_desc": "Who last modified the document",
        "company": "Company",
        "company_desc": "Organization that created the document",
        "created": "Creation Date",
        "created_desc": "When the document was created",
        "modified": "Modification Date",
        "modified_desc": "Last document modification",
        "last_printed": "Print Date",
        "last_printed_desc": "When the document was printed",
        "revision": "Revision Number",
        "revision_desc": "Version and change history",
        "version": "Document Version",
        "version_desc": "Document version number",
        "content_status": "Content Status",
        "content_status_desc": "Document readiness status",
        "category": "Category",
        "category_desc": "Thematic category",
        "language": "Document Language",
        "language_desc": "Content language",
        "identifier": "Identifier",
        "identifier_desc": "Unique document ID",
        "title": "Title",
        "title_desc": "Document title (preserved)",
        "subject": "Subject",
        "subject_desc": "Document subject matter (preserved)",
        "keywords": "Keywords",
        "keywords_desc": "Search tags (preserved)",
        "comments": "Comments",
        "comments_desc": "Content description (preserved)",
        "creator": "Creator",
        "creator_desc": "PDF creation software",
        "producer": "Producer",
        "producer_desc": "PDF generation software",
        "encoder": "Encoder",
        "encoder_desc": "Recording software/device",
        "creation_time": "Creation Date",
        "creation_time_desc": "Shooting/creation time",
        "location": "Location",
        "location_desc": "Location information",
        "major_brand": "Container Format",
        "major_brand_desc": "Main video file type",
        "compatible_brands": "Compatibility",
        "compatible_brands_desc": "Supported formats",
        "comment": "Comments",
        "comment_desc": "Brief description (preserved)",
        "description": "Description",
        "description_desc": "Detailed description (preserved)",
    },
}


class Translator:
    def __init__(self, language="ru"):
        self.language = language

    def set_language(self, language: str):
        if language in LOCALIZATION:
            self.language = language

    def get(self, key: str, **kwargs) -> str:
        translation = LOCALIZATION.get(self.language, {}).get(key, key)
        if kwargs:
            return translation.format(**kwargs)
        return translation


# Глобальный экземпляр
translator = Translator()
