name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    env:
      PYTHONIOENCODING: "utf-8"
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: pipx install poetry

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: poetry install

    - name: Check for outdated dependencies
      run: poetry show --outdated

    - name: Check for security vulnerabilities
      run: |
        poetry export -f requirements.txt --output requirements.txt --without-hashes
        pip install safety
        safety check -r requirements.txt
      continue-on-error: true
