name: Dependency Check

on:
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Check poetry.lock is up to date
      run: poetry lock --check

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Check for security vulnerabilities
      run: |
        poetry run safety check --json || echo "Security check completed with warnings"

    - name: Run tests with latest dependencies
      run: |
        poetry run python -m pytest tests/ -v --tb=short
